### PR TITLE
docs: add TypeScript type definition

### LINKED ISSUE #225: Include TypeScript definition
It'd be nice if this module came with TypeScript definitions. If it's still maintained, I could write them.

### PR DESCRIPTION
**Pull request by tmcw**
- Fixes #225

This adds TypeScript types for fastify-constraints. These are modeled mainly after the type defs for fastify-etags: https://github.com/fastify/fastify-etag/blob/master/types/index.d.ts

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
Can you please add tests for types? We normally do it via [tsd](https://www.npmjs.com/package/tsd). See for example the type tests in this repo https://github.com/nearform/fastify-ravendb/

**Comment by tmcw** [comment]
I've copied raven's setup almost exactly and it fails tests. Trying to figure out why, but any help would be apprecaited.

**Comment by simoneb** [comment]
it looks like tap is trying to run your test file

**Review by simoneb — COMMENTED** [review]
You need to execute tsd, or it won't do anything :)

**Review by simoneb — APPROVED** [review]

**Pull request merged**
